export const CONNECTION_INITIATE_RTC = 'CONNECTION_INITIATE_RTC';
export const CONNECTION_ADD_DATA_CHANNEL = 'CONNECTION_ADD_DATA_CHANNEL';
export const CONNECTION_CHANGE_HOST_OFFER = 'CONNECTION_CHANGE_HOST_OFFER';
export const CONNECTION_CHANGE_PEER_OFFER = 'CONNECTION_CHANGE_PEER_OFFER';
export const CONNECTION_NEXT_STEP = 'CONNECTION_NEXT_STEP';
export const CONNECTION_JOINED = 'CONNECTION_JOINED';
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED';
export const CONNECTION_INPUT_ERROR = 'CONNECTION_INPUT_ERROR';
export const CONNECTION_EMULATOR = 'CONNECTION_EMULATOR';

export const NOT_CONNECTED = 'NOT_CONNECTED';
export const JOINING = 'JOINING';
export const CREATING = 'CREATING';
export const CONNECTED = 'CONNECTED';

export const SENDING_MESSAGE = 'SENDING_MESSAGE';
export const TYPING_MESSAGE = 'TYPING_MESSAGE';
export const RECIEVED_MESSAGE = 'RECIEVED_MESSAGE';

export const SENDING_FILE = 'SENDING_FILE';

export const TOGGLE_EMOJI_LIST = 'TOGGLE_EMOJI_LIST';
export const EMOJI_CHANGE_CURRENT_CATEGORY = 'EMOJI_CHANGE_CURRENT_CATEGORY';
export const EMOJI_CHANGE_SCROLL_TOP = 'EMOJI_CHANGE_SCROLL_TOP';

export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const TOGGLE_SENDING_NOTIFICATIONS = 'TOGGLE_SENDING_NOTIFICATIONS';