export const CONNECTION_INITIATE_RTC = 'CONNECTION_INITIATE_RTC';
export const CONNECTION_ADD_DATA_CHANNEL = 'CONNECTION_ADD_DATA_CHANNEL';
export const CONNECTION_CHANGE_HOST_OFFER = 'CONNECTION_CHANGE_HOST_OFFER';
export const CONNECTION_CHANGE_PEER_OFFER = 'CONNECTION_CHANGE_PEER_OFFER';
export const CONNECTION_NEXT_STEP = 'CONNECTION_NEXT_STEP';
export const CONNECTION_JOINED = 'CONNECTION_JOINED';
export const CONNECTION_INPUT_ERROR = 'CONNECTION_INPUT_ERROR';

export const NOT_CONNECTED = 'NOT_CONNECTED';
export const JOINING = 'JOINING';
export const CREATING = 'CREATING';
export const CONNECTED = 'CONNECTED';

export const SENDING_MESSAGE = 'SENDING_MESSAGE';
export const TYPING_MESSAGE = 'TYPING_MESSAGE';
export const RECIEVED_MESSAGE = 'RECIEVED_MESSAGE';

export const TOGGLE_EMOJI_LIST = 'TOGGLE_EMOJI_LIST';
export const EMOJI_CHANGE_PAGE = 'EMOJI_CHANGE_PAGE';